trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: 'DataLoader'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'public/api'
    artifact: 'main'
