trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: yarn install --frozen-lockfile
  displayName: 'Restore npm packages'

- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: yarn webpack
  displayName: 'Build web app'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/deploy'
    artifact: 'deploy'
